add upload to s3
qutip/qutip-benchmark pull request #10
Opened 2022-08-11 14:55 UTC by xspronken

Adding the job that uploads the benchmarks to the S3 server to the workflow.

2022-08-13 22:35 UTC, xspronken commented
@hodgestar have the secrets you set up to connect to the s3 bucket been removed?

2022-08-15 14:08 UTC, hodgestar commented
The secrets are till there. Perhaps they aren't provided because this PR isn't from an fork?

2022-08-15 14:09 UTC, hodgestar approved these changes

2022-08-15 14:10 UTC, hodgestar requested changes
We should make sure this only runs on the main branch and only on this repo.

2022-08-23 14:49 UTC, hodgestar reviewed
From discussion: Let's
- copy run_benchmarks.yml to nightly_benchmarks.yml
- rename run_benchmarks.yml to test.yml
- have upload_S3.yml run only after nightly_benchmarks.yml
- change nightly benchmarks to run nightly.

2022-08-23 16:20 UTC, hodgestar commented on .github/workflows/run_benchmarks.yml
> +name: Nightly Benchmarks
The file still needs to be renamed to "nightly_benchmarks.yml".

2022-08-23 16:22 UTC, hodgestar commented on .github/workflows/upload_S3.yml
> +name: Upload S3
I'd like to suggest that we just add this as an additional job to the nightly_benchmarks.yml. It simplifies things a bit, and, in particular, means we can use the default github artifact action.

So:
```
jobs:
    benchmarks:
       ...
    upload_to_s3:
       depends-on: ["benchmarks"]
       ...
```

2022-08-23 16:33 UTC, xspronken commented on .github/workflows/run_benchmarks.yml
> +name: Nightly Benchmarks
Fixed in [faa9088](https://github.com/qutip/qutip-benchmark/pull/10/commits/faa9088d9dc9e0ebcc6e8500f505278e41ee1819).

2022-08-23 16:33 UTC, xspronken commented on .github/workflows/upload_S3.yml
> +name: Upload S3
I agree, I changed it in [fdf4eac](https://github.com/qutip/qutip-benchmark/pull/10/commits/fdf4eac49582c96e9f9ac0d4b9cef8dc7d296fb1).

2022-08-23 16:37 UTC, hodgestar commented on .github/workflows/nightly_benchmarks.yml
> +
```suggestion
  workflow_dispatch

```
Let's also add `workflow_dispatch` then we can push a button in the GitHub interface to run the action.

2022-08-23 16:38 UTC, hodgestar commented on .github/workflows/nightly_benchmarks.yml
> +
```suggestion
```

2022-08-23 16:39 UTC, hodgestar reviewed
Other than the last two small suggestions, looks good to me.

2022-08-24 20:36 UTC, hodgestar approved these changes

2022-08-24 20:37 UTC, hodgestar commented
@xspronken Happy for you to merge this when you're ready. Don't forget to write a nice merge commit message when you do.

2022-08-25 08:54 UTC, merged