change groups
qutip/qutip-benchmark pull request #22
Opened 2022-09-07 09:38 UTC by xspronken

Changing how the groups are defined.

2022-09-11 10:46 UTC, hodgestar requested changes
I suggested two kinds of changes

One is just naming spacing the group names, so that we can use that to automatically organize the benchmarks a bit if needed, and made the names a bit more readable.

The other is trying to reorganize the solver groups in a way that makes more sense to me.

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_lin_alg_QobjEvo.py
> +    benchmark.group = "Matmul_QobjEvo_op@ket"
```suggestion
    benchmark.group = "math:matmul:qobjevo-op-times-ket"
```

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    benchmark.group = "Add"
```suggestion
    benchmark.group = "math:add:op-plus-op"
```

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    benchmark.group = "Matmul_op@op"
```suggestion
    benchmark.group = "math:matmul:op-times-op"
```

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    benchmark.group = "Matmul_op@ket"
```suggestion
    benchmark.group = "math:matmul:op-times-ket"
```

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_solvers.py
> +    benchmark.group = "MeSolve"
```suggestion
    benchmark.group = f"solvers:master-equation:{model_solve.lower()}"
```
As explained before the group name should represent a task -- in this case solve the master equation for the given model.

I don't know if this will require changing anything in the plotting code or not, but I think it is the right organization for the group names.

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_solvers.py
> +    benchmark.group = "McSolve"
```suggestion
    benchmark.group = f"solvers:monte-carlo:{model_solve.lower()}
```

2022-09-11 10:46 UTC, hodgestar commented on benchmarks/tests/test_solvers.py
> +    benchmark.group = "SteadyState"
```suggestion
    benchmark.group = f"solvers:steadystate:{model_steady.lower()}
```

2022-09-12 16:24 UTC, xspronken commented on benchmarks/tests/test_solvers.py
> +    benchmark.group = "MeSolve"
Adding the model will involve changing the plotting functions, for it to remain the same something like `solvers:master-equation` would work. This is what I've done for now.
Should the model be needed, I can keep your suggestion for the group name and add what would be used for plot titles and file names to` benchmark.extra_info`.

2022-09-12 16:26 UTC, xspronken commented
We also should note that because the operation name is retrieved from the group, the benchmarks currently displayed on the website will have to be discarded or modified to fit with the new names.

2022-09-13 14:54 UTC, hodgestar approved these changes

2022-09-13 14:54 UTC, merged