add benchmark failure check
qutip/qutip-benchmark pull request #25
Opened 2022-09-07 20:55 UTC by xspronken

Add a job that fails the workflow if a benchmark fails.

2022-09-11 10:23 UTC, hodgestar commented
There is a much simpler and better way to achieve this because `pytest.main` returns the exit code.

```python
def run_benchmarks(args):
    "Run pytest benchmark with sensible defaults."
    pytest.main(
```
In `run_benchmark` above, change the first line to `return pytest.main(` so the exit code is returned.

Then in your own `def main` function change
```python
    run_benchmarks(other_args)
    benchmark_latest = get_latest_benchmark()
    add_packages_to_json(benchmark_latest)
```
Save the exit code in a variable, don't save the benchmarks if the exit code is not 0, and return the exit code from your function.

Finally, change the end of your script to:
```python
if __name__ == "__main__":
    sys.exit(main())
```

2022-09-11 10:25 UTC, hodgestar requested changes
There is a much simpler solution that just makes sure the correct exit code is returned. That will make the script do the right thing everywhere, and not require dubious matching of stdout.

I wrote a fuller description of the better solution as a comment.

2022-09-11 14:34 UTC, xspronken commented
This is indeed much better. I don't think there is a need to only save the benchmarks on exit code 0. They are saved automatically when running:
```
pytest.main(
        [
            "qutip_benchmark/benchmarks",
            "--benchmark-only",
            "--benchmark-columns=Mean,StdDev,rounds,Iterations",
            "--benchmark-sort=name",
            "--benchmark-autosave",
            "-Wdefault",
        ]
        + args
    )
```
This means they will be saved regardless of the exit code. I could delete the file if exit code is not 0 but i don't think this is useful, since the entire workflow stops on failure and all the subsequent jobs are cancelled. So regardless of whether the benchmarks are saved or not, if they fail they will not be uploaded to S3, nor will an artefact be created (see [here](https://github.com/qutip/qutip-benchmark/runs/8292381873?check_suite_focus=true)).

2022-09-11 17:12 UTC, hodgestar commented
If they are written already, happy for them to be kept.

2022-09-13 17:31 UTC, Ericgig approved these changes
Look good, but you will probably have a conflict merging this and #29.

2022-09-13 19:15 UTC, hodgestar commented on .github/workflows/nightly_benchmarks.yml
> +          python benchmarks/benchmarks.py -v -m nightly
```suggestion
          -m qutip_benchmark.cli.run_benchmarks -m nightly -v
```
Perhaps a bad merge?

2022-09-15 10:00 UTC, hodgestar commented on .github/workflows/nightly_benchmarks.yml
> +          -m qutip_benchmark.cli.run_benchmarks -m nightly -v
```suggestion
          python -m qutip_benchmark.cli.run_benchmarks -m nightly -v
```

2022-09-15 11:44 UTC, hodgestar approved these changes

2022-09-15 12:42 UTC, merged