Matmul and Add continuous benchmarks
qutip/qutip-benchmark pull request #5
Opened 2022-08-03 14:42 UTC by xspronken

1st PR for the qutip-benchmark GSoC project. This PR contains the tools to benchmark the Matmul and Add operations.

2022-08-03 20:38 UTC, Ericgig requested changes
Could you run `pycodestyle` or `black` to check the styling.
We require at least to follow pep8 for styling.

You could have only added the new files. This PR is about "Matmul and Add continuous benchmarks", not renaming old benchmarks.

2022-08-03 20:38 UTC, Ericgig commented on benchmarks/tests/test_linear_algebra.py
> +import scipy as sc
We do not shorten scipy and qutip.

2022-08-03 20:38 UTC, Ericgig commented on benchmarks/tests/test_linear_algebra.py
> +def matrix_2(matrix, size,density,dtype,request):
It skip the density and dtype parameters if it create an operator, so the pytest output will not match the operation.
Instead of this `matrix_2`, we could have 2 `matmul` tests: `test_matmul(matrix_right, matrix_left_oper_ket)` and `test_matmul_oper_ket(matrix, ket)`. This would make it easier to read the tests and results. And the 2 the timing and scaling of `op @ op` and `op @ vec` are different enough to deserve to be seems as 2 operations.

2022-08-03 20:38 UTC, Ericgig commented on benchmarks/tests/test_linear_algebra.py
> +    B = matrix
Let's not use one character variable names here.

2022-08-03 20:38 UTC, Ericgig commented on benchmarks/tests/test_linear_algebra.py
> +        return res
No dispatching on qutip's type here? Test for both `qutip_dense`, `qutip_csr` will be created.

2022-08-04 12:46 UTC, xspronken commented on README.md
> +organizations](https://qutip.org/#supporting-organizations).  Initial work on
Fixed in commit [155c24d](https://github.com/qutip/qutip-benchmark/pull/5/commits/155c24d6cc3c0cb4e065aa5e640a0888feedef5c).

2022-08-04 12:47 UTC, xspronken commented on benchmarks/benchmarks.py
> +
Fixed all the pep8 styling in commit [516d2a5](https://github.com/qutip/qutip-benchmark/pull/5/commits/516d2a53899b3f12f1297f4156f50044144842f6)

2022-08-04 12:50 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +import scipy as sc
fixed in commit [0944b01](https://github.com/qutip/qutip-benchmark/pull/5/commits/0944b01bc24fd54f1ecaf6844f45924efd7e0b3d). I wasn't sure whether to simply remove the shortening or import the specific functions used from the module so for now I simply removed the shortening.

2022-08-04 12:51 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +        return res
Added the dispatching based on the qutip type in commit [ec9599c](https://github.com/qutip/qutip-benchmark/pull/5/commits/ec9599cd9c55941a66265cf837a974bc91d149fd).

2022-08-04 12:53 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +    B = matrix
Fixed in commit [be2b3c0](https://github.com/qutip/qutip-benchmark/pull/5/commits/be2b3c0385982ed2d14f5cb3e1ee0eb1f6595ce9).

2022-08-04 12:53 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +def matrix_2(matrix, size,density,dtype,request):
Fixed in commit [be2b3c0](https://github.com/qutip/qutip-benchmark/pull/5/commits/be2b3c0385982ed2d14f5cb3e1ee0eb1f6595ce9).

2022-08-04 14:21 UTC, hodgestar reviewed
Generally looks good!

2022-08-04 14:21 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    return left+right
I would just move the function definition inside `test_add` since each benchmark needs its own method. We can put the function outside for benchmarks with more code.

2022-08-04 14:21 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    benchmark.group = group
It would be nice to write a small fixture that does this setting of the benchmark group.

2022-08-04 14:21 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +    benchmark.group = group
Happy for this to happen in a follow-up PR though.

2022-08-08 14:15 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +        return res.to(dtype[6:])
Here it would be a lot better to do:
```python
pkg, _, dtype = pkg_dtype.parition("_")
if pkg == 'numpy' and not dtype:
    ...
elif pkg == 'scipy' and dtype == 'csr':
    ...
elif pkg == 'qutip':
    ...
else:
    raise ValueError(f"Unknown package dtype: {pkg_dtype!r}")
```

2022-08-08 14:27 UTC, hodgestar commented on README.md
> +================
```suggestion
qutip-benchmark
===============
```

2022-08-08 14:28 UTC, hodgestar commented on README.md
> +To run the benchmarks first clone and install Qutip (this plugin is meant to run with qutip v5 which is not realeased yet).
```suggestion
To run the benchmarks first clone and install QuTiP (this package is meant to run with qutip v5 which is not realeased yet).
```

2022-08-08 14:29 UTC, Ericgig commented on benchmarks/tests/test_linear_algebra.py
> +@pytest.fixture(params=['numpy', 'scipy_csr', 'qutip_dense', 'qutip_csr'])
```suggestion
@pytest.fixture(params=['numpy', 'scipy_csr', 'dense', 'csr'], 
                ids=['numpy', 'scipy_csr', 'qutip_dense', 'qutip_csr'])
```

2022-08-08 14:29 UTC, hodgestar commented on benchmarks/tests/test_linear_algebra.py
> +        return res.to(dtype[6:])
Also happy with the simpler suggestion @xspronken made on the call, which is to add cases for `qutip_dense` and `qutip_csr`.

2022-08-08 15:28 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +        return res.to(dtype[6:])
Applied in [76c921d](https://github.com/qutip/qutip-benchmark/pull/5/commits/76c921d7ee1acb665616ac9d4ab54160ad388219).

2022-08-08 15:30 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +@pytest.fixture(params=['numpy', 'scipy_csr', 'qutip_dense', 'qutip_csr'])
I changed dtype handling in [76c921d](https://github.com/qutip/qutip-benchmark/pull/5/commits/76c921d7ee1acb665616ac9d4ab54160ad388219) so i don't think this is necessary anymore.

2022-08-08 15:30 UTC, xspronken commented on benchmarks/tests/test_linear_algebra.py
> +    return left+right
Applied in [71ffe37](https://github.com/qutip/qutip-benchmark/pull/5/commits/71ffe3761f661ccc934c049bacab4de29c0e4123).

2022-08-08 15:31 UTC, xspronken commented on README.md
> +================
Applied in [8868f33](https://github.com/qutip/qutip-benchmark/pull/5/commits/8868f338a5c05cb81e4cc2b1d8af55967e4f1e1f).

2022-08-08 15:31 UTC, xspronken commented on README.md
> +To run the benchmarks first clone and install Qutip (this plugin is meant to run with qutip v5 which is not realeased yet).
Applied in [8868f33](https://github.com/qutip/qutip-benchmark/pull/5/commits/8868f338a5c05cb81e4cc2b1d8af55967e4f1e1f).

2022-08-08 17:42 UTC, Ericgig approved these changes
Code look fine.
I would prefer that you check the pep8 before merging.

2022-08-08 18:53 UTC, merged